# Copyright (c) Meta Platforms, Inc. and affiliates.

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

sweep:
  dir: ${data_root}/runs/${experiment}/${now:%Y-%m-%d_%H%M%S}
  subdir: ${hydra.job.num}
